" rxvt exceptions: 256 colors, vertical bar in insert mode
if &term =~ "^rxvt"
  set t_Co=256
  let &t_SI .= "\<Esc>[5 q"
  let &t_EI .= "\<Esc>[2 q"
  silent !echo -ne "\033]12;white\007"
  autocmd VimLeave * silent !echo -ne "\033]112\007"
endif

" include SyntaxAttr
map -a :call SyntaxAttr#SyntaxAttr()<CR>

" remove trailing spaces on save
autocmd BufWritePre * %s/\s\+$//e

" expand tabs to 2 spaces
set expandtab
set tabstop=2
set shiftwidth=0

" disable swapfiles
set noswapfile

" mobility
set mouse=a               " click to move cursor
set whichwrap=b,s,<,>,[,] " auto wrap to next line

" move up/down by display lines
noremap  <buffer> <silent> k gk
noremap  <buffer> <silent> j gj
noremap  <buffer> <silent> 0 g0
noremap  <buffer> <silent> $ g$
onoremap <silent> j gj
onoremap <silent> k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

" aesthetics
set cul    " enable styling on cursor line
set number " display line numbers
set list   " display invisibles
set listchars=space:·,tab:»\ ,eol:¬

" highlight javascript in markdown files
let g:markdown_fenced_languages = ["javascript", "js=javascript"]

" syntax highlighting
syntax enable
colorscheme synthetic

" make background transparent
hi Normal guibg=NONE ctermbg=NONE
