" rxvt exceptions: 256 colors, vertical bar in insert mode
if &term =~ "^rxvt"
  set t_Co=256
  let &t_SI .= "\<Esc>[5 q"
  let &t_EI .= "\<Esc>[2 q"
  silent !echo -ne "\033]12;white\007"
  autocmd VimLeave * silent !echo -ne "\033]112\007"
endif

" remove trailing spaces on save
autocmd BufWritePre * %s/\s\+$//e

" include SyntaxAttr
map -a :call SyntaxAttr#SyntaxAttr()<CR>

" aesthetics
set cul    " enable styling on cursor line
set number " display line numbers
set list   " display invisibles
set listchars=space:·,tab:»\ ,eol:¬

" click to move cursor
set mouse=a

" automatically wrap to next line when x exceeds line width
set whichwrap=b,s,<,>,[,]

" expand tabs to 2 spaces
set expandtab
set tabstop=2
set shiftwidth=0

" disable swapfiles
set noswapfile

" highlight javascript in markdown files
let g:markdown_fenced_languages = ["javascript", "js=javascript"]

" syntax highlighting
syntax enable
colorscheme synthetic

" make background transparent
hi Normal guibg=NONE ctermbg=NONE
