#!/bin/sh
bspc rule -a Libreoffice state=tiled
bspc rule -a Peek state=floating
bspc config border_width 0
bspc config window_gap   8
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc monitor eDP1 -d 0 1
bspc monitor DP1 -d 2 3
