#!/bin/sh

feh --bg-fill --randomize --no-fehbg ~/media/pictures/wallpapers/*

bspc rule -a Libreoffice state=tiled
bspc config border_width 0
bspc config window_gap   8
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc monitor -d I II III IV

xcompmgr -c &
sxhkd

