#!/bin/sh
bspc monitor eDP1 -d 0 1
bspc monitor DP1 -d 2 3
bspc config border_width 1
bspc config window_gap   8
bspc config top_padding  16
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc rule -a "*" state=floating
